### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by debanjansen48** [kanryu/pmx#2]
~/Downloads/pmx$ pip install .
Processing /home/debanjan/Downloads/pmx
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.14 in /home/debanjan/.local/lib/python3.10/site-packages (from pmx==2.0+62.g96b48be7) (1.24.3)
Requirement already satisfied: scipy>=1.1 in /home/debanjan/.local/lib/python3.10/site-packages (from pmx==2.0+62.g96b48be7) (1.10.1)
Requirement already satisfied: matplotlib>=2.2 in /home/debanjan/.local/lib/python3.10/site-packages (from pmx==2.0+62.g96b48be7) (3.7.1)
**ERROR: Package 'pmx' requires a different Python: 3.10.10 not in '<3,>=2.7'**

~/Downloads/pmx$ python
Python 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by kanryu** [comment]
@debanjansen48 
pmx is NOT a pip package :(
